### ISSUE TITLE
Exception in thread "main": module java.desktop does not export sun.awt.X11 to unnamed module 0f78a47e

### ISSUE THREAD

**Issue by moonrisewarrior** [java-decompiler/jd-gui#183]
Hi,

I have installed jd-gui with the .deb file, but when I run it, it opens the splash screen, and closes after about 10 seconds.

I tried running with the "java -jar jd-gui-1.4.0.jar" command and file I found [here](https://github.com/java-decompiler/jd-gui/issues/148), but I got the following error:

```
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make member of class sun.awt.X11.XToolkit accessible:  module java.desktop does not export sun.awt.X11 to unnamed module @f78a47e
	at sun.reflect.Reflection.throwInaccessibleObjectException(java.base@9-internal/Reflection.java:420)
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-internal/AccessibleObject.java:174)
	at java.lang.reflect.Constructor.checkCanSetAccessible(java.base@9-internal/Constructor.java:183)
	at java.lang.reflect.Constructor.setAccessible(java.base@9-internal/Constructor.java:176)
	at org.codehaus.groovy.reflection.CachedConstructor$1.run(CachedConstructor.java:41)
	at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method)
	at org.codehaus.groovy.reflection.CachedConstructor.<init>(CachedConstructor.java:39)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:76)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:265)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:215)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:225)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:168)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:158)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:141)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:250)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:282)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:292)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:259)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:868)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createPojoMetaClassGetPropertySite(AbstractCallSite.java:338)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGetPropertySite(AbstractCallSite.java:314)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.acceptGetProperty(AbstractCallSite.java:299)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:291)
	at org.jd.gui.service.configuration.ConfigurationXmlPersisterProvider.load(ConfigurationXmlPersisterProvider.groovy:51)
	at org.jd.gui.service.configuration.ConfigurationPersister$load.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.jd.gui.App.main(App.groovy:27)
```

I am using Elementary OS 0.4 "Loki" 64-bit.

**Comment by jvelezVOX** [comment]
Same issue:

java -jar jd-gui-1.4.0.jar 
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make member of class sun.awt.X11.XToolkit accessible:  module java.desktop does not export sun.awt.X11 to unnamed module @644baf4a
	at sun.reflect.Reflection.throwInaccessibleObjectException(java.base@9-internal/Reflection.java:420)
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-internal/AccessibleObject.java:174)
	at java.lang.reflect.Constructor.checkCanSetAccessible(java.base@9-internal/Constructor.java:183)
	at java.lang.reflect.Constructor.setAccessible(java.base@9-internal/Constructor.java:176)
	at org.codehaus.groovy.reflection.CachedConstructor$1.run(CachedConstructor.java:41)
	at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method)
	at org.codehaus.groovy.reflection.CachedConstructor.<init>(CachedConstructor.java:39)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:76)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:265)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:215)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:225)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:168)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:158)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:141)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:250)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:282)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:292)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:259)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:868)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createPojoMetaClassGetPropertySite(AbstractCallSite.java:338)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGetPropertySite(AbstractCallSite.java:314)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.acceptGetProperty(AbstractCallSite.java:299)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:291)
	at org.jd.gui.service.configuration.ConfigurationXmlPersisterProvider.load(ConfigurationXmlPersisterProvider.groovy:51)
	at org.jd.gui.service.configuration.ConfigurationPersister$load.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.jd.gui.App.main(App.groovy:27)

**Comment by mlessio** [comment]
Same here:
```$ java -jar /opt/jd-gui/jd-gui.jar 
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make member of class sun.awt.X11.XToolkit accessible:  module java.desktop does not export sun.awt.X11 to unnamed module @f78a47e
	at sun.reflect.Reflection.throwInaccessibleObjectException(java.base@9-internal/Reflection.java:420)
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-internal/AccessibleObject.java:174)
	at java.lang.reflect.Constructor.checkCanSetAccessible(java.base@9-internal/Constructor.java:183)
	at java.lang.reflect.Constructor.setAccessible(java.base@9-internal/Constructor.java:176)
	at org.codehaus.groovy.reflection.CachedConstructor$1.run(CachedConstructor.java:41)
	at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method)
	at org.codehaus.groovy.reflection.CachedConstructor.<init>(CachedConstructor.java:39)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:76)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:265)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:215)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:225)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:168)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:158)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:141)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:250)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:282)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:292)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:259)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:868)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createPojoMetaClassGetPropertySite(AbstractCallSite.java:338)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGetPropertySite(AbstractCallSite.java:314)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.acceptGetProperty(AbstractCallSite.java:299)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:291)
	at org.jd.gui.service.configuration.ConfigurationXmlPersisterProvider.load(ConfigurationXmlPersisterProvider.groovy:51)
	at org.jd.gui.service.configuration.ConfigurationPersister$load.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.jd.gui.App.main(App.groovy:27)
```

**Comment by emmanue1** [comment]
Could you try the last version (1.4.1) and give me a feedback ?

**Comment by arcadien** [comment]
maybe you should just run the application using JVM parameter:
```--add-exports=java.desktop/sun.awt.X11=ALL-UNNAMED```
