### ISSUE TITLE
Java 9 Compatibility

### ISSUE THREAD

**Issue by stuxuhai** [java-decompiler/jd-gui#187]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/Applications/JD-GUI.app/Contents/Resources/Java/jd-gui-1.4.0.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make jdk.internal.loader.ClassLoaders$AppClassLoader(jdk.internal.loader.ClassLoaders$PlatformClassLoader,jdk.internal.loader.URLClassPath) accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @2a17b7b6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:192)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:185)
	at org.codehaus.groovy.reflection.CachedConstructor$1.run(CachedConstructor.java:41)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.reflection.CachedConstructor.<init>(CachedConstructor.java:39)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:76)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:265)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:215)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:225)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:168)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:158)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:141)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:250)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:282)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:292)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:259)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:868)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createPojoSite(CallSiteArray.java:122)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:163)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at org.jd.gui.view.MainDescription.run(MainDescription.groovy:170)
	at groovy.util.FactoryBuilderSupport.build(FactoryBuilderSupport.java:1169)
	at groovy.util.FactoryBuilderSupport.build(FactoryBuilderSupport.java:1152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:161)
	at org.jd.gui.view.MainView$_closure1.doCall(MainView.groovy:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at groovy.swing.SwingBuilder$_edt_closure1.doCall(SwingBuilder.groovy:333)
	at groovy.swing.SwingBuilder$_edt_closure1.doCall(SwingBuilder.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at groovy.lang.Closure.run(Closure.java:504)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by slavus** [comment]
+1

**Comment by intellitour** [comment]
+1

**Comment by fjh658** [comment]
JDK9 add new feature "module",  access restricted class of some module.

modify universalJavaApplicationStub.sh

or

workaround  

``` shell
java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar /Applications/JD.app/Contents/Resources/Java/jd-gui-1.4.0.jar
```

**Comment by intellitour** [comment]
@fjh658 thank you very much! The solution works like a charm!

**Comment by yzhang226** [comment]
it works
+1

**Comment by rajeshkarthik** [comment]
it works as mentioned +1

**Comment by MewX** [comment]
+1, it's been a long time not updated

**Comment by elisongomes** [comment]
@fjh658 Thanks!! This solution work great!

**Comment by vjindal50** [comment]
how do i access  Info.plist for jdk9 on mac

**Comment by vjindal50** [comment]
java.lang.reflect.InaccessibleObjectException: Unable to make field java.util.ArrayList jdk.internal.loader.URLClassPath.loaders accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @baa1719

i am getting this error

**Comment by elisongomes** [comment]
@vjindal50 go to Applications folder, select JD-GUI.app, right button "Show Package Contents", navigate in Contents. Done, the Info.plist file is here.

**Comment by SmallBlueWhale** [comment]
Thank for your help!,it does work @fjh658

**Comment by aiamuzz** [comment]
okay ... i am having crashes on Linux ...
so should i be running this command ?

`java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar /Applications/JD.app/Contents/Resources/Java/jd-gui-1.4.0.jar`

**Comment by aiamuzz** [comment]
i tried running the above command ... but gives out the following error ...

`Error: Unable to access jarfile /Applications/JD.app/Contents/Resources/Java/jd-gui-1.4.0.jar`

**Comment by zqhong** [comment]
@aiamuzz 
Make sure the file `/Applications/JD.app/Contents/Resources/Java/jd-gui-1.4.0.jar` exists.

You can:
```bash
$ wget https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui-1.4.0.jar
$ java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar
```

It works for me. The above is my java version.
```bash
$ java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

**Comment by aiamuzz** [comment]
ok ... @zqhong  ... thanks for the bypass/alternate method ...

the straight way would have been installing the deb package and launching the app ... 

your command ...

> java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar

works ... a working JD-GUI ...

hope the devs are going to fix it to work the straight way ...

**Comment by JomaCorpFX** [comment]
java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar 

Windows 10 Pro
Java 9
ty. Works like a charm.

![captura de pantalla 70](https://user-images.githubusercontent.com/18097869/36454800-69012d70-166b-11e8-939d-44f3aaf6fcb4.png)

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by youyouStorm** [comment]
+1

**Comment by Atomin-Lee** [comment]
Thanks a lot, it looks like the project is dead.

**Comment by dequn** [comment]
Thanks.

**Comment by saatomic** [comment]
On Kali Linux:
```
$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-1, mixed mode)
```

`java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar` works great for me as suggested by ` fjh658 commented on Sep 29, 2017`

**Comment by 0xCGonzalo** [comment]
Nice! Many thanks!

Run directly the .jar worth it too

**Comment by skiy** [comment]
Nice + 1

**Comment by ryenus** [comment]
FYI, I did a quick check and couldn't find a pull request for the fix discussed here, so I just created #217.

**Comment by sonicarg** [comment]
> >=JDK9 add new feature "module", access restricted class of some module.
> 
> modify Info.plist
> ![image](https://user-images.githubusercontent.com/5550316/33947517-86db748c-e05f-11e7-82e5-75be983caf55.png)
> 
> ![image](https://user-images.githubusercontent.com/5550316/31000753-ac9fbc70-a4a3-11e7-8487-36598b1ba30b.png)
> ![image](https://user-images.githubusercontent.com/5550316/31000769-bee15fa6-a4a3-11e7-8523-d7f380a56c65.png)
> 
> VMOptions=-Xms512m --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED
> 
> or
> modify universalJavaApplicationStub.sh
> 
> or
> 
> workaround
> 
> ```shell
> macOS
> java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar /Applications/JD.app/Contents/Resources/Java/jd-gui-1.4.0.jar
> 
> win/linux
> java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar
> ```
> 
> @slavus @intellitour

Confirming fix works on Java 10.0.2 Windows x64. A neat way to open JD is to create a bat/cmd file and type:

```
@echo off
java -Xms512m --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar
```

**Comment by fruitdish** [comment]
on manjaro 
this problem fiexed
```
java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar 
```
it works,thanks

**Comment by SnowballGo** [comment]
On windows 10 :
it works,thanks

**Comment by hummatli** [comment]
on manjaro
Java 11

java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar 

This works,thanks

**Comment by dhoard** [comment]
For Mac / Java 11 you can install the DMG, then edit ...

```
/Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
```

... adding ...

```
--add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED
```

Example ...

```
        exec "$JAVACMD" \
                        --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED \
                        -cp "${JVMClassPath}" \
                        -Xdock:icon="${ResourcesFolder}/${CFBundleIconFile}" \
                        -Xdock:name="${CFBundleName}" \
                        ${JVMOptions:+$JVMOptions }\
                        ${JVMDefaultOptions:+$JVMDefaultOptions }\
                        ${JVMMainClass}\
                        ${JVMArguments:+ $JVMArguments}
```

**Comment by emmanue1** [comment]
Groovy libraries updated.

**Comment by xmeng1** [comment]
after update `compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.5.8', ext: 'pom'` ,the error gone

**Comment by Tuo018** [comment]
> >=JDK9 add new feature "module", access restricted class of some module.
> 
> modify Info.plist
> ![image](https://user-images.githubusercontent.com/5550316/33947517-86db748c-e05f-11e7-82e5-75be983caf55.png)
> 
> ![image](https://user-images.githubusercontent.com/5550316/31000753-ac9fbc70-a4a3-11e7-8487-36598b1ba30b.png)
> ![image](https://user-images.githubusercontent.com/5550316/31000769-bee15fa6-a4a3-11e7-8523-d7f380a56c65.png)
> 
> VMOptions=-Xms512m --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED
> 
> or
> modify universalJavaApplicationStub.sh
> 
> or
> 
> workaround
> 
> ```shell
> macOS
> java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar /Applications/JD.app/Contents/Resources/Java/jd-gui-1.4.0.jar
> 
> win/linux
> java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar
> ```
> 
> @slavus @intellitour

hey, i have a similar pb like `Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make jdk.internal.loader.ClassLoaders$AppClassLoader(jdk.internal.loader.ClassLoaders$PlatformClassLoader,jdk.internal.loader.URLClassPath) accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @45f08579
`
and my library is `  compile group: 'com.github.snowindy', name: 'scriptlet4docx', version: '0.8.6'`

**Comment by damogallagher** [comment]
I am hitting this issue in my Kotlin Spring Boot based app. I tried the versions as mentioned by different folks in this thread.
I am trying to run my code locally using Amazon Coretto 11 as I use this JDK when installing on Elastic beanstalk
My PowermockIgnore annotation is as follows
`@PowerMockIgnore("javax.management.", "com.sun.org.apache.xerces.", "javax.xml.", "org.xml.", "org.w3c.dom.",
    "com.sun.org.apache.xalan.", "javax.activation.*", "javax.xml.transform.*", "com.sun.org.apache.xalan.*")`

The error I receive is
```

java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.lang.String,boolean) throws java.lang.ClassNotFoundException accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @d5ce97f
	at org.powermock.core.classloader.DeferSupportingClassLoader.findResource(DeferSupportingClassLoader.java:154)
	at java.base/java.lang.ClassLoader.findResource(ClassLoader.java:1342)
	at java.base/java.lang.Module.getResourceAsStream(Module.java:1575)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsResourceLoader.loadResource(BuiltInsResourceLoader.java:27)
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClassFinder.findBuiltInsData(ReflectKotlinClassFinder.kt:52)
	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInsPackageFragmentProvider.findPackage(JvmBuiltInsPackageFragmentProvider.kt:60)`
``
