### ISSUE TITLE
Errors during 'save all sources'

### ISSUE THREAD

**Issue by aapo** [java-decompiler/jd-gui#19]
With git-head 55c4321710c728903d2469a3b1d6eaf2872e2437
Decompiling of jar seems to work, but 'save all sources' causes:

    Undefined type catch
    java.lang.Throwable: NameGenerator.generateParameterNameFromSignature: invalid signature 'TT;'
            at jd.core.process.analyzer.variable.DefaultVariableNameGenerator.generateLocalVariableNameFromSignature(DefaultVariableNameGenerator.java:106)
            at jd.core.process.analyzer.classfile.LocalVariableAnalyzer.GenerateLocalVariableNames(LocalVariableAnalyzer.java:1733)
            at jd.core.process.analyzer.classfile.LocalVariableAnalyzer.Analyze(LocalVariableAnalyzer.java:206)
            at jd.core.process.analyzer.classfile.ClassFileAnalyzer.PreAnalyzeMethods(ClassFileAnalyzer.java:698)
            at jd.core.process.analyzer.classfile.ClassFileAnalyzer.AnalyzeClass(ClassFileAnalyzer.java:126)
            at jd.core.process.analyzer.classfile.ClassFileAnalyzer.Analyze(ClassFileAnalyzer.java:84)
            at jd.core.process.DecompilerImpl.decompile(DecompilerImpl.java:37)
            at jd.gui.service.sourcesaver.ClassFileSourceSaverProvider.save(ClassFileSourceSaverProvider.java:83)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:38)
            at jd.gui.service.sourcesaver.ZipFileSourceSaverProvider.save(ZipFileSourceSaverProvider.groovy:38)
            at jd.gui.spi.SourceSaver$save$1.call(Unknown Source)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:68)
            at jd.gui.service.mainpanel.ContainerPanelFactoryProvider$ContainerPanel.save(ContainerPanelFactoryProvider.groovy:104)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
            at jd.gui.controller.SaveAllSourcesController$1.run(SaveAllSourcesController.groovy:60)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Undefined type catch
    Undefined type catch
    Undefined type catch
    ConstantPool.addConstantClass: invalid name index
    ConstantPool.addConstantClass: invalid name index
    ConstantPool.addConstantClass: invalid name index
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    java.lang.Throwable: NameGenerator.generateParameterNameFromSignature: invalid signature 'TE;'
            at jd.core.process.analyzer.variable.DefaultVariableNameGenerator.generateLocalVariableNameFromSignature(DefaultVariableNameGenerator.java:106)
            at jd.core.process.analyzer.classfile.LocalVariableAnalyzer.GenerateLocalVariableNames(LocalVariableAnalyzer.java:1733)
            at jd.core.process.analyzer.classfile.LocalVariableAnalyzer.Analyze(LocalVariableAnalyzer.java:206)
            at jd.core.process.analyzer.classfile.ClassFileAnalyzer.PreAnalyzeMethods(ClassFileAnalyzer.java:698)
            at jd.core.process.analyzer.classfile.ClassFileAnalyzer.AnalyzeClass(ClassFileAnalyzer.java:126)
            at jd.core.process.analyzer.classfile.ClassFileAnalyzer.Analyze(ClassFileAnalyzer.java:84)
            at jd.core.process.DecompilerImpl.decompile(DecompilerImpl.java:37)
            at jd.gui.service.sourcesaver.ClassFileSourceSaverProvider.save(ClassFileSourceSaverProvider.java:83)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at jd.gui.service.sourcesaver.PackageSourceSaverProvider.save(PackageSourceSaverProvider.groovy:19)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:55)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
            at jd.gui.service.sourcesaver.DirectorySourceSaverProvider.save(DirectorySourceSaverProvider.groovy:38)
            at jd.gui.service.sourcesaver.ZipFileSourceSaverProvider.save(ZipFileSourceSaverProvider.groovy:38)
            at jd.gui.spi.SourceSaver$save$1.call(Unknown Source)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:68)
            at jd.gui.service.mainpanel.ContainerPanelFactoryProvider$ContainerPanel.save(ContainerPanelFactoryProvider.groovy:104)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
            at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
            at jd.gui.controller.SaveAllSourcesController$1.run(SaveAllSourcesController.groovy:60)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch
    Undefined type catch

System is Ubuntu-14.04, and java version:

    java version "1.8.0_45"
    Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by emmanue1** [comment]
It looks like an issue in JD-Core. Could you send your CLASS file by mail to java.decompiler at gmail.com? I cant promise to fix it quickly : I'm focus on publishing JD projects on GitHub.

**Comment by FesterCluck** [comment]
I know this is very old, but I'm running into the same issue and I can't seem to understand the problem. Can you tell me why this was marked as invalid, or if there was any resolution?
