### ISSUE TITLE
 invalid CEN header (encrypted entry)

### ISSUE THREAD

**Issue by mohanr** [java-decompiler/jd-gui#193]
Does this have anything to do with obfuscation of the decompiled class files ? I do see the method names in the left panel. But when I try to view the source I see this error.

> Exception in thread "AWT-EventQueue-0" java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: java.util.zip.ZipError: invalid CEN header (encrypted entry)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.util.zip.ZipError: invalid CEN header (encrypted entry)
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at java_util_concurrent_Future$get.call(Unknown Source)
        at org.jd.gui.controller.MainController$3.getIndex(MainController.groovy:510)
        at org.jd.gui.view.component.TypePage$_indexesChanged_closure6.doCall(TypePage.groovy:318)

**Comment by TehJumpingJawa** [comment]
The archive is probably compressed with an unsupported compression type.

Java's built in zip/jar library supports only type 0 (uncompressed) and
type 8 (deflate).

Try decompressing the jar with a 3rd party tool, then either recompressing
with type 0/8 or working directly off the extracted classes.

**Comment by mohanr** [comment]
I have decompressed the class files. When I try to open one of them I see this. But I see the method in the left panel.
As you suggested I also compresses them again using 'jar' and tried to open the class files.
Same error.

**Comment by java-decompiler** [comment]
Hi. Without any other information, I can simply suggest you try again with the latest version.
