### ISSUE TITLE
NullPointer exception when loading simple class file

### ISSUE THREAD

**Issue by glacambre** [java-decompiler/jd-gui#280]
```
>uname -a
Linux 5.0.0-1030-oem-osp1 #34-Ubuntu SMP Tue Nov 19 10:30:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
>java --version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
>javac --version
javac 13.0.1
```
JD-GUI version: 1.6.5
JD-Core version: 1.1.12

Hi, thank you for working on jd-gui! I'm encountering a NullPointerException when I try to load a class file:
<details>
>java -jar ~/downloads/jd-gui-1.6.5.jar /tmp/main.class
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.jd.gui.service.treenode.DirectoryTreeNodeFactoryProvider.make(DirectoryTreeNodeFactoryProvider.java:38)
        at org.jd.gui.service.mainpanel.ContainerPanelFactoryProvider$ContainerPanel.<init>(ContainerPanelFactoryProvider.java:59)
        at org.jd.gui.service.mainpanel.ContainerPanelFactoryProvider.make(ContainerPanelFactoryProvider.java:43)
        at org.jd.gui.service.fileloader.AbstractFileLoaderProvider.load(AbstractFileLoaderProvider.java:41)
        at org.jd.gui.service.fileloader.AbstractTypeFileLoaderProvider.load(AbstractTypeFileLoaderProvider.java:49)
        at org.jd.gui.service.fileloader.ClassFileLoaderProvider.load(ClassFileLoaderProvider.java:36)
        at org.jd.gui.service.uriloader.FileUriLoaderProvider.load(FileUriLoaderProvider.java:28)
        at org.jd.gui.controller.MainController.openURI(MainController.java:558)
        at org.jd.gui.controller.MainController.openFiles(MainController.java:455)
        at org.jd.gui.controller.MainController.lambda$show$28(MainController.java:125)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</details>
It also happens when try to load the class file through the GUI:
<details>
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.jd.gui.service.treenode.DirectoryTreeNodeFactoryProvider.make(DirectoryTreeNodeFactoryProvider.java:38)
        at org.jd.gui.service.mainpanel.ContainerPanelFactoryProvider$ContainerPanel.<init>(ContainerPanelFactoryProvider.java:59)
        at org.jd.gui.service.mainpanel.ContainerPanelFactoryProvider.make(ContainerPanelFactoryProvider.java:43)
        at org.jd.gui.service.fileloader.AbstractFileLoaderProvider.load(AbstractFileLoaderProvider.java:41)
        at org.jd.gui.service.fileloader.AbstractTypeFileLoaderProvider.load(AbstractTypeFileLoaderProvider.java:49)
        at org.jd.gui.service.fileloader.ClassFileLoaderProvider.load(ClassFileLoaderProvider.java:36)
        at org.jd.gui.service.uriloader.FileUriLoaderProvider.load(FileUriLoaderProvider.java:28)
        at org.jd.gui.controller.MainController.openURI(MainController.java:558)
        at org.jd.gui.controller.MainController.openFiles(MainController.java:455)
        at org.jd.gui.controller.MainController.openFile(MainController.java:434)
        at org.jd.gui.controller.MainController.onOpen(MainController.java:200)
        at org.jd.gui.controller.MainController.lambda$null$0(MainController.java:88)
        at org.jd.gui.util.swing.SwingUtil$1.actionPerformed(SwingUtil.java:158)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:349)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:975)
        at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
        at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
        at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
        at java.desktop/javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
        at java.desktop/javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:311)
        at java.desktop/javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:297)
        at java.desktop/javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2993)
        at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2985)
        at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
        at java.desktop/java.awt.Component.processEvent(Component.java:6413)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4893)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</details>

The class file was just compiled from the following source code:
```java
class main {
        public static void main(String args[]) {
        }
}
```

You can download the class file here: [main.zip](https://github.com/java-decompiler/jd-gui/files/3987490/main.zip)

**Comment by glacambre** [comment]
I was also wondering, as I couldn't find out from JD-GUI's website, does JD-GUI lets you visualize a class's StackMap Table? That's the one thing I'm interested in :).
