### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

### ISSUE THREAD

**Issue by bobo880917** [java-decompiler/jd-gui#349]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
I get this error

**Comment by pdinc-oss** [comment]
jd-gui-1.6.6.jar on windows...

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.jd.gui.service.treenode.DirectoryTreeNodeFactoryProvider.make(DirectoryTreeNodeFactoryProvider.java:38)
        at org.jd.gui.service.mainpanel.ContainerPanelFactoryProvider$ContainerPanel.<init>(ContainerPanelFactoryProvider.java:59)
        at org.jd.gui.service.mainpanel.ContainerPanelFactoryProvider.make(ContainerPanelFactoryProvider.java:43)
        at org.jd.gui.service.fileloader.AbstractFileLoaderProvider.load(AbstractFileLoaderProvider.java:41)
        at org.jd.gui.service.fileloader.AbstractTypeFileLoaderProvider.load(AbstractTypeFileLoaderProvider.java:49)
        at org.jd.gui.service.fileloader.ClassFileLoaderProvider.load(ClassFileLoaderProvider.java:36)
        at org.jd.gui.service.uriloader.FileUriLoaderProvider.load(FileUriLoaderProvider.java:28)
        at org.jd.gui.controller.MainController.openURI(MainController.java:558)
        at org.jd.gui.controller.MainController.openFiles(MainController.java:455)
        at org.jd.gui.controller.MainController.openFile(MainController.java:434)
        at org.jd.gui.controller.MainController.onOpen(MainController.java:200)
        at org.jd.gui.controller.MainController.lambda$null$0(MainController.java:88)
        at org.jd.gui.util.swing.SwingUtil$1.actionPerformed(SwingUtil.java:158)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
        at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)


java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

**Comment by CodingTarik** [comment]
same error, getting this only if I am opening first ".java" file in a package. 

Windows 11
java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
