### ISSUE TITLE
Save All source dose not work

### ISSUE THREAD

**Issue by limelect** [java-decompiler/jd-gui#35]
On JD-GUI 1.1.0 Save all source dose not work.
It worked on ver 0.3.6
Neither preferences 
Using window 7

**Comment by emmanue1** [comment]
Have you a stacktrace on the console with jd-gui.x.y.z.jar ?

**Comment by limelect** [comment]
I do not understand your comment
I am executing jd-gui.exe (Jd_Gui_110)
As i said 0.3.6 workes

**Comment by limelect** [comment]
Ok i found what happened. The zip output dose not open a screen
to choose where to save the zip location
as it was on 0.3.6.

HOWEVER preferences dose not open 
On 0.3.6 it dose

**Comment by limelect** [comment]
Very strange i deleted the zip
and now it dose not do it i should have saved it.

**Comment by gechdcb** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke method isActivated() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at jd.gui.controller.MainController.onSaveAllSources(MainController.groovy:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
        at jd.gui.controller.MainController$_show_closure5$_closure25.doCall(MainController.groovy:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at groovy.swing.impl.DefaultAction.actionPerformed(DefaultAction.java:38)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$400(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by limelect** [comment]
I am trying to use only  jd-gui.exe so your comment dose not make sense.

**Comment by asbachb** [comment]
The exe ist just a wrapper around the jar. 
I just tested an export of all source with commons-collections-3.2.1.jar which worked fine. It seems the problem depends on the lib you want to export.

**Comment by limelect** [comment]
The answer is Not logical
why SAME code workes with version 0.3.6 .

**Comment by pdeva** [comment]
i have tried on both mac and windows and can confirm this issue exists on both platforms.
Tried with version 1.1.0

**Comment by pdeva** [comment]
it seems if you download the source and run it from within the ide, the issue is not reproducible. Seems like something wrong with the release binary.

**Comment by emmanue1** [comment]
I add some controls, in MainController, to be sure that the background initialization is complete.

**Comment by pdeva** [comment]
ok running from source again, it seems i managed to reproduce the issue:

```
Exception in thread "pool-1-thread-1" java.util.ServiceConfigurationError: jd.gui.spi.PreferencesPanel: Provider jd.gui.service.preferencespanel.UITabsPreferencesProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.toList(DefaultGroovyMethods.java:2910)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.toList(DefaultGroovyMethods.java:2929)
	at org.codehaus.groovy.runtime.dgm$637.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at jd.gui.service.preferencespanel.PreferencesPanelService.<init>(PreferencesPanelService.groovy:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:230)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:234)
	at jd.gui.service.preferencespanel.PreferencesPanelService.getInstance(PreferencesPanelService.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1845)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3735)
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:291)
	at jd.gui.controller.MainController$1.run(MainController.groovy:147)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    jd/gui/service/preferencespanel/UITabsPreferencesProvider.<init>()V @99: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b800 1b4c 04bd 001d 5903 2b12 1e32 1220
    0x0000010: 03b8 0026 04b8 0026 b900 2c04 0053 5910
    0x0000020: ff12 04b8 0032 2a5f ab00 0000 0000 0076
    0x0000030: 0000 0004 aca4 66ff 0000 002c e7e9 2bb5
    0x0000040: 0000 0041 0000 9b75 0000 005d 0013 85ff
    0x0000050: 0000 0066 5f5a 5903 3212 34b8 0038 c000
    0x0000060: 345f 57b7 003b a700 425f 5a59 0332 1234
    0x0000070: b800 38c0 0034 5f59 0432 b800 415f 57b7
    0x0000080: 0044 a700 265f 5a57 b700 46a7 001d 5f5a
    0x0000090: 5903 32b8 0041 5f57 b700 49a7 000d bb00
    0x00000a0: 4b59 124d b700 50bf 572a b600 544d 2c2a
    0x00000b0: 5fb5 0056 2c57 2b12 5732 1259 125b b900
    0x00000c0: 5e03 004e 2d12 59b8 0038 c000 592a 5fb5
    0x00000d0: 0060 2d57 2b12 6132 2a2a b400 60b9 0065
    0x00000e0: 0300 57b1                              
  Stackmap Table:
    full_frame(@84,{UninitializedThis,Object[#105]},{Object[#107],UninitializedThis})
    full_frame(@105,{UninitializedThis,Object[#105]},{Object[#107],UninitializedThis})
    full_frame(@133,{UninitializedThis,Object[#105]},{Object[#107],UninitializedThis})
    full_frame(@142,{UninitializedThis,Object[#105]},{Object[#107],UninitializedThis})
    full_frame(@158,{UninitializedThis,Object[#105]},{Object[#107],UninitializedThis})
    full_frame(@168,{Object[#2],Object[#105]},{Object[#107]})

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getConstructor0(Class.java:3062)
	at java.lang.Class.newInstance(Class.java:403)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 35 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke method show() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at jd.gui.controller.MainController.onPreferences(MainController.groovy:288)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
	at jd.gui.controller.MainController$_show_closure5$_closure40.doCall(MainController.groovy:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at groovy.swing.impl.DefaultAction.actionPerformed(DefaultAction.java:38)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by huangyg11** [comment]
save all not work. 

download sha1 73b29841dd23edcb077acd8aad6f6ae67d73fef3 and compile in os 10.10.3.

run from commandline, click save all to dir 'src'. only an empty dir src is created, without any source files. and nothing in the command line

**Comment by emmanue1** [comment]
What is your JVM version? What is your architecture? Have you a stacktrace?

**Comment by huangyg11** [comment]
I find the files were saved actually but just not where I choose.  The files were saved to the same dir with the jd-gui-1.2.0.jar file.

**Comment by emmanue1** [comment]
What is your operating system & version? What is your JVM version?

**Comment by huangyg11** [comment]
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

By the way, I find the decompiled result is not as better as the engine used in the intellij. For example, a variable appeared without declaring in the jd result while normal in the intellij result. So I use Intellij engine in my work.

**Comment by emmanue1** [comment]
Fernflower (https://github.com/fesh0r/fernflower), the decompiler used by IntellJ, is better than JD-Core today... so, you do the right choice.

About the issue, "Save All" works for me with JVM 1.7.0_40, 1.7.0_75, 1.8.0, 1.8.0_40 : #7

**Comment by JustGregory** [comment]
@limelect - Navigate to the location of your jd-gui and then check the file properties dialog for the files in the directory. I know for a certainty that, depending on how a person downloads the files, the OS can "mark" executables (.exe, .jar, whatever) as being from another computer (which, of course, it ''is''); also, check whether you can set the "Run as Administrator" option on it.

At least, it's been in my experience to check such things FIRST when something does not run....

**Comment by TehJumpingJawa** [comment]
This is still present in current 1.4.0 windows release.

Have jd-gui.exe on the desktop.
- run it
- use it to decompile a load of classes.
- save all sources -> select a folder (any folder, doesn't make a difference) -> enter a file name "test" -> click 'save'
- jd-gui creates a sub-folder "test" within the folder I selected, but then writes the decompiled classes to the desktop. (jd-gui's working directory)

**Comment by emmanue1** [comment]
Hi TehJumpingJawa, I fail to reproduce this bug.. A question:
Step 3) you write "test" as the file name, you click on "Save"
Step 4) JD-GUI creates a subfolder "test" on the target directory ?
Sorry to ask you this, but, have you some screenshots ?

**Comment by TehJumpingJawa** [comment]
1) jd-gui (1.4.0) is run from here:
https://dl.dropboxusercontent.com/u/54785909/jd-gui/1.png

2) Class file being decompiled (HelloWorld.class) is here:
https://dl.dropboxusercontent.com/u/54785909/jd-gui/2.png

3) "Save All Sources" targeted here, with "Flibble" being the desired output name:
https://dl.dropboxusercontent.com/u/54785909/jd-gui/3.png

4) Decompiled HelloWorld.java is erroneously written to the jd-gui working directory:
https://dl.dropboxusercontent.com/u/54785909/jd-gui/4.png

5) The intended target gets a directory created in it called "Flibble":
https://dl.dropboxusercontent.com/u/54785909/jd-gui/5.png

**Comment by emmanue1** [comment]
Thanks, it's clear. I fix that.
