### ISSUE TITLE
 java.lang.RuntimeException: Zip entry 'org/' tries to escape target directory

### ISSUE THREAD

**Issue by lizhichao999** [java-decompiler/jd-gui#447]
use cmd java -cp java-decompiler.jar org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler -dgs=true bin/*.jar decode

Exception in thread "main" java.lang.RuntimeException: Zip entry 'org/' tries to escape target directory
        at org.jetbrains.java.decompiler.struct.StructContext.addArchive(StructContext.java:143)
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:86)
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:64)
        at org.jetbrains.java.decompiler.main.Fernflower.addSource(Fernflower.java:73)
        at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.addSource(ConsoleDecompiler.java:111)
        at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.main(ConsoleDecompiler.java:79)

**Comment by Dsi13nc3** [comment]
I solved this problem by this method
https://github.com/FabricMC/intellij-fernflower/issues/20#issuecomment-1322282624
