### ISSUE TITLE
Application simply not doing anything

### ISSUE THREAD

**Issue by Ninesideddevelopment** [java-decompiler/jd-gui#453]
I'm on windows 11 and I'm using JD-GUI 1.6.6. I have tried the windows exe and the .jar file, but neither worked. I selected the .class file I wanted to decompile, but nothing actually happened. No errors, no signs of the application doing anything. I'm not sure what to do.

**Comment by WilliamDOliveira** [comment]
same problem...

**Comment by smfukaya** [comment]
Check https://github.com/java-decompiler/jd-gui/issues/448#issuecomment-2307153572

**Comment by rkdevs** [comment]
> Check [#448 (comment)](https://github.com/java-decompiler/jd-gui/issues/448#issuecomment-2307153572)

I am having the same issue as OP in 2025 and referenced your comment @smfukaya, however the resolution posted in the linked comment is not working for me. For Win 10/11 and JD-GUI v.1.6.6, I am seeing the following exception:

> `Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Unsupported class file major version 59
>         at org.b.a.e.<init>(Unknown Source)
>         at org.b.a.e.<init>(Unknown Source)
>         at org.b.a.e.<init>(Unknown Source)
>         at org.b.a.e.<init>(Unknown Source)
>         at org.jd.gui.service.fileloader.ClassFileLoaderProvider.load(Unknown Source)
>         at org.jd.gui.service.uriloader.FileUriLoaderProvider.load(Unknown Source)
>         at org.jd.gui.a.c.openURI(Unknown Source)
>         at org.jd.gui.a.c.b(Unknown Source)
>         at org.jd.gui.a.c.b(Unknown Source)
>         at org.jd.gui.a.c.w(Unknown Source)
>         at org.jd.gui.c.i.b.actionPerformed(Unknown Source)
>         at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
>         at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
>         at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
>         at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
>         at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
>         at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
>         at java.awt.Component.processMouseEvent(Unknown Source)
>         at javax.swing.JComponent.processMouseEvent(Unknown Source)
>         at java.awt.Component.processEvent(Unknown Source)
>         at java.awt.Container.processEvent(Unknown Source)
>         at java.awt.Component.dispatchEventImpl(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Window.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)`

I seeing this exception when using the bat file to start & use JD-GUI on windows. 

> `"JAVA_NEWER_HOME\bin\java.exe" -Djava.util.Arrays.useLegacyMergeSort=true -jar "PATH_TO_JD\jd-gui.exe"`

Where the JAVA_HOME versions I've tried are jdk1.8.0_202 and jdk-12.0.2 so far, resulting in the above exception. Has anyone been able to run and use JD-GUI v1.6.6 on windows recently?

Note: I downloaded the .zip file from [jd-gui-windows-1.6.6.zip](https://github.com/java-decompiler/jd-gui/releases/download/v1.6.6/jd-gui-windows-1.6.6.zip)

Thanks!

**Comment by StevenJack666** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Boat2017** [comment]
现在是假期。已经收到您的来信，我会尽快回复。

**Comment by smfukaya** [comment]
> > Check [#448 (comment)](https://github.com/java-decompiler/jd-gui/issues/448#issuecomment-2307153572)
> 
> I am having the same issue as OP in 2025 and referenced your comment [@smfukaya](https://github.com/smfukaya), however the resolution posted in the linked comment is not working for me. For Win 10/11 and JD-GUI v.1.6.6, I am seeing the following exception:
> 
> > `Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Unsupported class file major version 59 at org.b.a.e.<init>(Unknown Source) at org.b.a.e.<init>(Unknown Source) at org.b.a.e.<init>(Unknown Source) at org.b.a.e.<init>(Unknown Source) at org.jd.gui.service.fileloader.ClassFileLoaderProvider.load(Unknown Source) at org.jd.gui.service.uriloader.FileUriLoaderProvider.load(Unknown Source) at org.jd.gui.a.c.openURI(Unknown Source) at org.jd.gui.a.c.b(Unknown Source) at org.jd.gui.a.c.b(Unknown Source) at org.jd.gui.a.c.w(Unknown Source) at org.jd.gui.c.i.b.actionPerformed(Unknown Source) at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) at javax.swing.DefaultButtonModel.setPressed(Unknown Source) at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) at java.awt.Component.processMouseEvent(Unknown Source) at javax.swing.JComponent.processMouseEvent(Unknown Source) at java.awt.Component.processEvent(Unknown Source) at java.awt.Container.processEvent(Unknown Source) at java.awt.Component.dispatchEventImpl(Unknown Source) at java.awt.Container.dispatchEventImpl(Unknown Source) at java.awt.Component.dispatchEvent(Unknown Source) at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) at java.awt.Container.dispatchEventImpl(Unknown Source) at java.awt.Window.dispatchEventImpl(Unknown Source) at java.awt.Component.dispatchEvent(Unknown Source) at java.awt.EventQueue.dispatchEventImpl(Unknown Source) at java.awt.EventQueue.access$500(Unknown Source) at java.awt.EventQueue$3.run(Unknown Source) at java.awt.EventQueue$3.run(Unknown Source) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) at java.awt.EventQueue$4.run(Unknown Source) at java.awt.EventQueue$4.run(Unknown Source) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) at java.awt.EventQueue.dispatchEvent(Unknown Source) at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) at java.awt.EventDispatchThread.pumpEvents(Unknown Source) at java.awt.EventDispatchThread.pumpEvents(Unknown Source) at java.awt.EventDispatchThread.run(Unknown Source)`
> 
> I seeing this exception when using the bat file to start & use JD-GUI on windows.
> 
> > `"JAVA_NEWER_HOME\bin\java.exe" -Djava.util.Arrays.useLegacyMergeSort=true -jar "PATH_TO_JD\jd-gui.exe"`
> 
> Where the JAVA_HOME versions I've tried are jdk1.8.0_202 and jdk-12.0.2 so far, resulting in the above exception. Has anyone been able to run and use JD-GUI v1.6.6 on windows recently?
> 
> Note: I downloaded the .zip file from [jd-gui-windows-1.6.6.zip](https://github.com/java-decompiler/jd-gui/releases/download/v1.6.6/jd-gui-windows-1.6.6.zip)
> 
> Thanks!

Hi @rkdevs,

My [#448 (comment)](https://github.com/java-decompiler/jd-gui/issues/448#issuecomment-2307153572) fixes the Open File Dialog (without it, it won't list any files of your system) and file drag n' drop.

If your Open File Dialog is working and you are getting the error `Unsupported class file major version 59` after you select the class or JAR file, it is because the target file was compiled with Java 15 (check [major versions](https://mkyong.com/java/list-of-java-class-file-major-version-numbers/)) but you are running jd with a lower JVM version (8 or 12).

Use JVM 15 to run jd and try to open the target file again.

Best.

**Comment by rkdevs** [comment]
> Hi [@rkdevs](https://github.com/rkdevs),
> 
> My [#448 (comment)](https://github.com/java-decompiler/jd-gui/issues/448#issuecomment-2307153572) fixes the Open File Dialog (without it, it won't list any files of your system) and file drag n' drop.
> 
> If your Open File Dialog is working and you are getting the error `Unsupported class file major version 59` after you select the class or JAR file, it is because the target file was compiled with Java 15 (check [major versions](https://mkyong.com/java/list-of-java-class-file-major-version-numbers/)) but you are running jd with a lower JVM version (8 or 12).
> 
> Use JVM 15 to run jd and try to open the target file again.
> 
> Best.

Hi @smfukaya,

Appreciate your response on trying to provide a solution for the issue I posted about. I tried using Java 15, as you suggested, and am still running into the same issue. I wonder if any more config changes are needed for JD-GUI to function. I even tried using another .class file but the same error message is returning in the cmd window while running the batch file.

I tried using JDK 15 as:
`C:\Program Files\Java\jdk-15\bin\java.exe" -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:\Downloads\jd-gui-windows-1.6.6\jd-gui.exe`

Thanks!

**Comment by smfukaya** [comment]
Hi @rkdevs,

Make sure that jd-gui.exe is using the JDK you specified. Open cmd.exe run the following command and check if the CommandLine matches '"C:\Program Files\Java\jdk-15\bin\java.exe" -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:\Downloads\jd-gui-windows-1.6.6\jd-gui.exe"':

`wmic process where caption="java.exe" get commandline,processid`

Best
