### ISSUE TITLE
Can't install jd-gui-1.6.6.deb on Linux Mint 22 Wilma

### ISSUE THREAD

**Issue by lotnikov** [java-decompiler/jd-gui#459]
Hello!
I downloaded [jd-gui-1.6.6.deb]([jd-gui-1.6.6.deb](https://github.com/java-decompiler/jd-gui/releases/download/v1.6.6/jd-gui-1.6.6.deb)) and installed it as usual, no errors appeared.
The package looks installed:
`me@legion:~$ apt list jd-gui
Listing... Done
jd-gui/now 1.6.6-0 all [installed,local]`

But no menu item appeared, and from the descriptions available in the project on github I couldn't figure out how to launch jd-gui from terminal, so can't add any more details..
Thanks

**Comment by lotnikov** [comment]
```
me@legion:/opt/jd-gui$ java -jar jd-gui.jar 
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:186)
	at org.jd.gui.service.a.c.a(Unknown Source)
	at org.jd.gui.App.main(Unknown Source)
me@legion:/opt/jd-gui$ echo "$XDG_SESSION_TYPE"
x11
me@legion:/opt/jd-gui$ env | grep DISPLAY
DISPLAY=:0
me@legion:/opt/jd-gui$ 
```

**Comment by 12471220** [comment]
Hey there, I encountered the same problem, have you solved it?
