### ISSUE TITLE
Unable to open preferences nor save all sources

### ISSUE THREAD

**Issue by babs** [java-decompiler/jd-gui#7]
After the apps is freshly started, few seconds later, I have the following trace[1].
Then any attempt to open preferences or save all sources as ends up in another trace[2] without showing any dialog.

D.

[1]

        Exception in thread "pool-1-thread-1" java.util.ServiceConfigurationError: jd.gui.spi.PreferencesPanel: Provider jd.gui.service.preferencespanel.DirectoryIndexerPreferencesProvider could not be instantiated
                at java.util.ServiceLoader.fail(ServiceLoader.java:232)
                at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
                at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
                at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
                at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
                at org.codehaus.groovy.runtime.DefaultGroovyMethods.toList(DefaultGroovyMethods.java:2910)
                at org.codehaus.groovy.runtime.DefaultGroovyMethods.toList(DefaultGroovyMethods.java:2929)
                at org.codehaus.groovy.runtime.dgm$637.invoke(Unknown Source)
                at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
                at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
                at jd.gui.service.preferencespanel.PreferencesPanelService.<init>(PreferencesPanelService.groovy:12)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
                at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
                at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:230)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:234)
                at jd.gui.service.preferencespanel.PreferencesPanelService.getInstance(PreferencesPanelService.groovy)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:483)
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
                at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1845)
                at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3735)
                at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:48)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:291)
                at jd.gui.controller.MainController$1.run(MainController.groovy:148)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)
        Caused by: java.lang.VerifyError: Bad <init> method call from inside of a branch
        Exception Details:
          Location:
            jd/gui/service/preferencespanel/DirectoryIndexerPreferencesProvider.<init>()V @91: invokespecial
          Reason:
            Error exists in the bytecode
          Bytecode:
            0x0000000: b800 254c 04bd 0027 5903 2b12 2832 122a
            0x0000010: b900 3002 0053 5910 ff12 04b8 0036 2a5f
            0x0000020: ab00 0000 0000 0076 0000 0004 aca4 66ff
            0x0000030: 0000 002c e7e9 2bb5 0000 0041 0000 9b75
            0x0000040: 0000 005d 0013 85ff 0000 0066 5f5a 5903
            0x0000050: 3212 38b8 003c c000 385f 57b7 003f a700
            0x0000060: 425f 5a59 0332 1238 b800 3cc0 0038 5f59
            0x0000070: 0432 b800 455f 57b7 0048 a700 265f 5a57
            0x0000080: b700 4aa7 001d 5f5a 5903 32b8 0045 5f57
            0x0000090: b700 4da7 000d bb00 4f59 1251 b700 54bf
            0x00000a0: 5701 4d2c 1256 b800 3cc0 0056 2a5f b500
            0x00000b0: 582c 572b 1259 3212 5bb9 005e 0200 4e2d
            0x00000c0: 125b b800 3cc0 005b 2a5f b500 602d 572a
            0x00000d0: b600 643a 0419 042a 5fb5 0066 1904 572b
            0x00000e0: 1267 322a 2b12 6832 126a 2b12 6b32 2b12
            0x00000f0: 6c32 126e b200 70b8 0076 b900 7a03 0012
            0x0000100: 7cb9 007a 0300 b900 7e03 002b 127f 3212
            0x0000110: 2ab9 005e 0200 b900 8304 0057 2b12 8432
            0x0000120: 1286 b900 3002 003a 0519 0512 86b8 003c
            0x0000130: c000 862a 5fb5 0088 1905 572b 1289 322b
            0x0000140: 128a 322a b400 88b9 005e 0200 2ab9 007a
            0x0000150: 0300 572b 128b 322a 2ab4 0088 2b12 8c32
            0x0000160: 122a b900 5e02 00b9 0083 0400 572b 128d
            0x0000170: 322a b400 88b9 005e 0200 3a06 1906 125b
            0x0000180: b800 3cc0 005b 2a5f b500 8f19 0657 b1  
          Stackmap Table:
            full_frame(@76,{UninitializedThis,Object[#147]},{Object[#149],UninitializedThis})
            full_frame(@97,{UninitializedThis,Object[#147]},{Object[#149],UninitializedThis})
            full_frame(@125,{UninitializedThis,Object[#147]},{Object[#149],UninitializedThis})
            full_frame(@134,{UninitializedThis,Object[#147]},{Object[#149],UninitializedThis})
            full_frame(@150,{UninitializedThis,Object[#147]},{Object[#149],UninitializedThis})
            full_frame(@160,{Object[#2],Object[#147]},{Object[#149]})

                at java.lang.Class.getDeclaredConstructors0(Native Method)
                at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
                at java.lang.Class.getConstructor0(Class.java:3062)
                at java.lang.Class.newInstance(Class.java:403)
                at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
                ... 35 more

[2]

        Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke method show() on null object
                at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
                at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
                at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
                at jd.gui.controller.MainController.onPreferences(MainController.groovy:289)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:483)
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
                at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
                at jd.gui.controller.MainController$_show_closure5$_closure40.doCall(MainController.groovy:134)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:483)
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
                at groovy.lang.Closure.call(Closure.java:423)
                at groovy.lang.Closure.call(Closure.java:439)
                at groovy.swing.impl.DefaultAction.actionPerformed(DefaultAction.java:38)
                at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
                at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
                at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
                at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
                at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
                at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
                at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
                at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
                at java.awt.Component.processMouseEvent(Component.java:6525)
                at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
                at java.awt.Component.processEvent(Component.java:6290)
                at java.awt.Container.processEvent(Container.java:2234)
                at java.awt.Component.dispatchEventImpl(Component.java:4881)
                at java.awt.Container.dispatchEventImpl(Container.java:2292)
                at java.awt.Component.dispatchEvent(Component.java:4703)
                at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
                at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
                at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
                at java.awt.Container.dispatchEventImpl(Container.java:2278)
                at java.awt.Window.dispatchEventImpl(Window.java:2739)
                at java.awt.Component.dispatchEvent(Component.java:4703)
                at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
                at java.awt.EventQueue.access$400(EventQueue.java:97)
                at java.awt.EventQueue$3.run(EventQueue.java:697)
                at java.awt.EventQueue$3.run(EventQueue.java:691)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
                at java.awt.EventQueue$4.run(EventQueue.java:719)
                at java.awt.EventQueue$4.run(EventQueue.java:717)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
                at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by babs** [comment]
using 1.0.0-rc2

**Comment by emmanue1** [comment]
Oh ! What is your JVM version?

**Comment by emmanue1** [comment]
java version "1.7.0-ea"
Java(TM) SE Runtime Environment (build 1.7.0-ea-b76)
Java HotSpot(TM) Client VM (build 17.0-b05, mixed mode)
-> KO: java.lang.reflect.MalformedParameterizedTypeException :collision:

java version "1.7.0_40"
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) 64-Bit Server VM (build 24.0-b56, mixed mode)
-> OK

java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)
-> OK

java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
-> OK

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
-> OK

**Comment by babs** [comment]
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) Server VM (build 25.20-b23, mixed mode)

**Comment by babs** [comment]
I'll try to update to latest

**Comment by babs** [comment]
Mea culpa, it owrks on 1.8.0_40.

Sorry :/
