### ISSUE TITLE
NPE because of uninitialized ASTORE signatures in FastCodeExceptionAnalyzer

### ISSUE THREAD

**Issue by bgandon** [java-decompiler/jd-gui#81]
With jd-core 0.7.1, I got this NPE in `CompareInstructionVisitor`:
```
Caused by: java.lang.NullPointerException: null
	at jd.core.process.analyzer.classfile.visitor.CompareInstructionVisitor.visit(CompareInstructionVisitor.java:57)
	at jd.core.process.analyzer.instruction.fast.visitor.FastCompareInstructionVisitor.visit(FastCompareInstructionVisitor.java:91)
	at jd.core.process.analyzer.instruction.fast.visitor.FastCompareInstructionVisitor.visit(FastCompareInstructionVisitor.java:23)
	at jd.core.process.analyzer.instruction.fast.FastCodeExceptionAnalyzer.Format142_RemoveFinallyInstructionsBeforeReturnAndCompactStoreReturn(FastCodeExceptionAnalyzer.java:2555)
	at jd.core.process.analyzer.instruction.fast.FastCodeExceptionAnalyzer.Format142(FastCodeExceptionAnalyzer.java:2508)
	at jd.core.process.analyzer.instruction.fast.FastCodeExceptionAnalyzer.FormatFastTry(FastCodeExceptionAnalyzer.java:1953)
	at jd.core.process.analyzer.instruction.fast.FastInstructionListBuilder.CreateFastTry(FastInstructionListBuilder.java:858)
	at jd.core.process.analyzer.instruction.fast.FastInstructionListBuilder.Build(FastInstructionListBuilder.java:144)
```

The code that produces the error is the following.

```java
public class FailingArrayInFinally {

    public Properties loadProps(File file) {
        Properties props = new Properties();
        InputStream input = null;
        try {
            input = new FileInputStream(file);
            props.load(input);
        } catch (IOException exc) {
            throw new RuntimeException(exc);
        } finally {
            close(input);
        }
        return props;
    }

    public static void close(Closeable... closeables) {
        for (Closeable closeable : closeables) {
            if (closeable == null) {
                continue;
            }
            try {
                closeable.close();
            } catch (IOException exc) {
            }
        }
    }
}
```

The problem is that the `close(input)` in the `finally` clause actually creates an array. When `FastCompareInstructionVisitor` compares the instructions, signatures of array instructions are compared in `CompareInstructionVisitor`. But they are all `null` at this step.

I managed to workaround this issue with this code, that I call from within the first loop of `ClassFileAnalyzer.AnalyzeMethods(ReferenceMap, HashMap, ClassFile)`:

```java
    public static void computeMissingArrayStoreSignatures(ClassFile classFile) {
        for (Method meth : classFile.getMethods()) {
            for (Instruction instruction : meth.getInstructions()) {
                if ((instruction.opcode != AASTORE) && (instruction.opcode != ARRAYSTORE)) {
                    continue;
                }
                ArrayStoreInstruction arrayStore = (ArrayStoreInstruction) instruction;
                if (arrayStore.signature == null) {
                    arrayStore.signature = arrayStore.getReturnedSignature(classFile.getConstantPool(),
                            meth.getLocalVariables());
                }
            }
        }
    }
```

I can also help you with a junit test I wrote on this.

**Comment by emmanue1** [comment]
The recognition of "try-catch-finally" statements, in JD-Core 0.7.1, looks like a labyrinth. This part of code became unmaintainable. I'm working on new decompiler.
Thanks for this feedback. I close this issue : this is not a GUI bug.
