### ISSUE TITLE
Exception in thread "main" java.awt.HeadlessException

### ISSUE THREAD

**Issue by JonathonReinhart** [java-decompiler/jd-gui#87]
Just experienced a [`java.awt.HeadlessException`](http://docs.oracle.com/javase/7/docs/api/java/awt/HeadlessException.html) when trying to launch jd-gui, after installing from [jd-gui-1.4.0-0.noarch.rpm](https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui-1.4.0-0.noarch.rpm):

```
$ java -jar /opt/jd-gui/jd-gui.jar 
Exception in thread "main" java.awt.HeadlessException
	at sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:73)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:291)
	at org.jd.gui.service.configuration.ConfigurationXmlPersisterProvider.load(ConfigurationXmlPersisterProvider.groovy:51)
	at org.jd.gui.service.configuration.ConfigurationPersister$load.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.jd.gui.App.main(App.groovy:27)

$ cat /etc/redhat-release 
Fedora release 22 (Twenty Two)
$ gnome-shell --version
GNOME Shell 3.16.3
$ java -version
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b27)
OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode)
$ dnf list installed | grep -i java
abrt-java-connector.x86_64             1.1.0-4.fc22                     @System 
devassistant-dap-java.noarch           0.11.1-1.fc22                    @System 
java-1.8.0-openjdk-headless.x86_64     1:1.8.0.60-14.b27.fc22           @updates
javapackages-tools.noarch              4.3.2-6.fc22                     @System 
python3-javapackages.noarch            4.3.2-6.fc22                     @System 
tzdata-java.noarch                     2015f-1.fc22                     @updates
```

**Comment by JonathonReinhart** [comment]
Turns out that Fedora defaults to a "headless" installation of Java.

I fixed this by installing the `java-1.8.0-openjdk` package:

```
$ sudo dnf install java-1.8.0-openjdk
```
